# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-07 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0002_auto_20180307_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='precip',
        ),
        migrations.AddField(
            model_name='reading',
            name='wind_dir',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
