# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-07 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0003_auto_20180307_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='wind_dir',
            field=models.CharField(max_length=100),
        ),
    ]
