# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-07 03:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0004_auto_20180307_0313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reading',
            old_name='wind_dir',
            new_name='precip',
        ),
    ]
